### PR TITLE
Add support for CTE(Common Table Expressions)

### PR DESCRIPTION
**Pull request by ionutursuleanu**

### CODE REVIEW

**Comment by ionutursuleanu** [comment]
Here's an example
```sql
WITH regional_sales AS (  SELECT region,
                                  SUM (amount) AS total_sales
                             FROM orders
                         GROUP BY region),
      top_regions AS (SELECT region
                        FROM regional_sales
                       WHERE total_sales > (SELECT SUM (total_sales) / 10
                                              FROM regional_sales)) 
  SELECT region,
         product,
         SUM (quantity) AS product_units,
         SUM (amount) AS product_sales
    FROM orders
   WHERE region IN (SELECT region
                      FROM top_regions)
GROUP BY region,
         product
```

**Comment by ionutursuleanu** [comment]
Or maybe like this?

```sql
WITH regional_sales AS (
      SELECT region,
             SUM (amount) AS total_sales
        FROM orders
    GROUP BY region 
), 
 top_regions AS (
    SELECT region
      FROM regional_sales
     WHERE total_sales > (SELECT SUM (total_sales) / 10
                            FROM regional_sales) 
) 
  SELECT region,
         product,
         SUM (quantity) AS product_units,
         SUM (amount) AS product_sales
    FROM orders
   WHERE region IN (SELECT region
                      FROM top_regions)
GROUP BY region,
         product
```
For this type of formatting I'll need to push some changes not included in this PR. Personally, I like this one more

**Comment by trask** [comment]
I'm good with either formatting

**Comment by ionutursuleanu** [comment]
> I'm good with either formatting

The second example then. I will make a new PR with updated `SqlParser.js` after merging this & #6

**Pull request merged**
